"""Adicionar payment_method e category na tabela Transaction

Revision ID: e48a1cbda7e7
Revises: 4d112a4be41e
Create Date: 2025-09-21 17:37:44.897300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48a1cbda7e7'
down_revision = '4d112a4be41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
